# POST http://localhost:3003/api/blogs
# content-type: application/json

# {
#   "title": "1984",
#   "author": "George Orwell",
#   "url": "www.1984.com",
#   "likes": "24"
# }

# POST http://localhost:3003/api/users
# content-type: application/json

# {
#   "username": "mluukkai",
#   "name": "Matti Luukkainen",
#   "password": "salainennn"
# }

# POST http://localhost:3003/api/users
# content-type: application/json

# {
#   "username": "hellas",
#   "name": "Arto Hellas",
#   "password": "hellas"
# }

# POST http://localhost:3003/api/login
# content-type: application/json

# {
#   "username": "mluukkai",
#   "password": "salainennn"
# }

# POST http://localhost:3003/api/login
# content-type: application/json

# {
#   "username": "root",
#   "password": "salainen"
# }

# POST http://localhost:3003/api/blogs
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2OWFlNzJjMmU1ZjNhMzU3MDg0N2Y3OWQiLCJpYXQiOjE3NzMwNDA1MTQsImV4cCI6MTc3MzA0NDExNH0.DnHW0tIpN0zJswhUBunCNMo6MMVrt6cofhKrQWVc58A

# {
#   "title": "The Joel Test: 12 Steps to Better Code",
#   "author": "Joel Spolsky",
#   "url": "https://www.joelonsoftware.com/2000/08/09/the-joel-test-12-steps-to-better-code/",
#   "likes": 0,
#   "user": "69ae72c2e5f3a3570847f79d"
# }

PUT http://localhost:3003/api/blogs/69ae77111faf7e78a8010849
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2OWFlNzJjMmU1ZjNhMzU3MDg0N2Y3OWQiLCJpYXQiOjE3NzMwNDQ4MzcsImV4cCI6MTc3MzA0ODQzN30.4MbM-dXeAdAutaiHEXaG3Q2M6EDY7adjne_S5NzGDbI

{
  "title": "The Joel Test: 12 Steps to Better Code",
  "author": "Joel Spolsky",
  "url": "https://www.joelonsoftware.com/2000/08/09/the-joel-test-12-steps-to-better-code/",
  "likes": 2,
  "user": "69a0650e0cd7039f0ec3d48b"
}

# DELETE http://localhost:3003/api/blogs
# content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY5YTA2NTBlMGNkNzAzOWYwZWMzZDQ4YiIsImlhdCI6MTc3MjE4MjIxNiwiZXhwIjoxNzcyMTg1ODE2fQ.ienIMArOboEAwegWYD55jxvqijGXLZsS0rdgdI8EdSQ

# {
#   "username": "root",
#   "password": "salainen",
#   "title": "Canonical string reduction",
#   "author": "Edsger W. Dijkstra",
#   "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
#   "likes": 12,
#   "user": "69a0650e0cd7039f0ec3d48b"
# }