# POST http://localhost:3001/api/persons
# content-type: application/json

# {
#     "name": "Georgy Zhukov",
#     "number": "12-234567"
# }

GET http://localhost:3001/api/persons
content-type: application/json